
import DAO.DAOInfoSalud;
import javax.swing.JOptionPane;
import pocos.InfoSalud;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josuecg
 */
public final class GUIModificarInfMedica extends javax.swing.JFrame {
    DAOInfoSalud daoInfo = new DAOInfoSalud();
    boolean registroNuevo = false;
    /**
     * Creates new form GUIModificarInfMedica
     * @param infoSalud
     */
     public GUIModificarInfMedica(InfoSalud infoSalud) {
        if(infoSalud.getNumeroSeguro()==null){
            registroNuevo = true;
        }
        initComponents();
        cargarEstaturas();
        cargarPeso();
        cargarInfoMedica(infoSalud);
        this.lbNombreEstudiante.setText(CRUD.estudianteObtenido.getNombreCompleto());
    }
    
    
    public GUIModificarInfMedica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbNombreEstudiante = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbNoSeguro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbSeguroTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cbTipoSangre = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbEstatura = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbDiscVisual = new javax.swing.JComboBox<>();
        chbDiabetes = new javax.swing.JCheckBox();
        chbHiper = new javax.swing.JCheckBox();
        cbPeso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setText("INFORMACIÓN MEDICA");

        lbNombreEstudiante.setText("<nombre_estudiante>");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Número de seguro");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de seguro");

        cbSeguroTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar seguro --", "ISSSTE", "INSABI", "SEGURO POPULAR", "IMSS", "Sin seguro" }));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setText("Tipo de sangre");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar tipo --", "O Negativo", "O Positivo", "A Negativo", "A Positivo", "B Negativo", "B Positivo", "AB Negativo", "AB Positivo" }));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Peso");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Estatura");

        cbEstatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecionar estatura --" }));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setText("Discapacidad visual");

        cbDiscVisual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar --", "Hipermetropia", "Astigmatismo", "Miopía", "Ceguera parcial", "Ceguera completa" }));

        chbDiabetes.setText("Diabetes");

        chbHiper.setText("Hipertensión");

        cbPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar peso --" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(cbSeguroTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(cbTipoSangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbNoSeguro))
                            .addComponent(chbDiabetes)
                            .addComponent(btnCancelar))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbHiper)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnGuardar)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbEstatura, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbDiscVisual, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbPeso, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbNombreEstudiante))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNombreEstudiante)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSeguroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDiscVisual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDiabetes)
                    .addComponent(chbHiper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarInfoMedica(InfoSalud infoSalud){
        if(infoSalud.getIdInfo()!=0){
            this.tbNoSeguro.setText(infoSalud.getNumeroSeguro());
            this.cbEstatura.setSelectedItem(infoSalud.getEstatura());
            this.cbSeguroTipo.setSelectedItem(infoSalud.getTipoSeguro());
            this.cbTipoSangre.setSelectedItem(infoSalud.getTipoSangre());
            this.cbPeso.setSelectedItem(infoSalud.getPeso());
            this.cbDiscVisual.setSelectedItem(infoSalud.getDiscVisual());
            if(infoSalud.getHipertención().equals("s")){
                this.chbHiper.setSelected(true);
            }
            if(infoSalud.getDiabetes().equals("s")){
                this.chbDiabetes.setSelected(true);
            }
        }
    }
    
    public void cargarEstaturas(){
        for(int i=130;i<=210;i++){
            this.cbEstatura.addItem(i+" cm");
        }
    }
    
    public void cargarPeso(){
        for(int i=35;i<=150;i++){
            this.cbPeso.addItem(i+"kg");
        }
    }

    public int validarCombos(){
        int validos = 0;
        if(this.cbDiscVisual.getSelectedIndex()==0 || this.cbEstatura.getSelectedIndex()==0 || 
                this.cbPeso.getSelectedIndex()==0 || this.cbSeguroTipo.getSelectedIndex()==0 || 
                this.cbTipoSangre.getSelectedIndex()==0){
            validos = 1;
        }
        return validos;
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       GUIInfoMedica infoMedica = new GUIInfoMedica();
       infoMedica.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       if(validarCombos()==0){
           if(registroNuevo){
           if(this.tbNoSeguro.getText().equals("")){
               InfoSalud infoGuardar = new InfoSalud();
               infoGuardar.setNumeroSeguro("Sin seguro");
               infoGuardar.setDiscVisual(this.cbDiscVisual.getSelectedItem().toString());
               infoGuardar.setEstatura(this.cbEstatura.getSelectedItem().toString());
               infoGuardar.setPeso(this.cbPeso.getSelectedItem().toString());
               infoGuardar.setTipoSangre(this.cbTipoSangre.getSelectedItem().toString());
               infoGuardar.setTipoSeguro(this.cbSeguroTipo.getSelectedItem().toString());
               if(this.chbDiabetes.isSelected()){
                   infoGuardar.setDiabetes("s");
               }else{
                   infoGuardar.setDiabetes("n");
               }
               if(this.chbHiper.isSelected()){
                   infoGuardar.setHipertención("s");
               }else{
                   infoGuardar.setHipertención("n");
               }
               daoInfo.registrarInfMedica(infoGuardar, CRUD.estudianteObtenido.getIdEstudiante());
           }else{
               InfoSalud infoGuardar = new InfoSalud();
               infoGuardar.setNumeroSeguro(this.tbNoSeguro.getText());
               infoGuardar.setDiscVisual(this.cbDiscVisual.getSelectedItem().toString());
               infoGuardar.setEstatura(this.cbEstatura.getSelectedItem().toString());
               infoGuardar.setPeso(this.cbPeso.getSelectedItem().toString());
               infoGuardar.setTipoSangre(this.cbTipoSangre.getSelectedItem().toString());
               infoGuardar.setTipoSeguro(this.cbSeguroTipo.getSelectedItem().toString());
               if(this.chbDiabetes.isSelected()){
                   infoGuardar.setDiabetes("s");
               }else{
                   infoGuardar.setDiabetes("n");
               }
               if(this.chbHiper.isSelected()){
                   infoGuardar.setHipertención("s");
               }else{
                   infoGuardar.setHipertención("n");
               }
               daoInfo.registrarInfMedica(infoGuardar, CRUD.estudianteObtenido.getIdEstudiante());
           }
       }else{
           if(this.tbNoSeguro.getText().equals("")){
               InfoSalud infoGuardar = new InfoSalud();
               infoGuardar.setNumeroSeguro("Sin seguro");
               infoGuardar.setDiscVisual(this.cbDiscVisual.getSelectedItem().toString());
               infoGuardar.setEstatura(this.cbEstatura.getSelectedItem().toString());
               infoGuardar.setPeso(this.cbPeso.getSelectedItem().toString());
               infoGuardar.setTipoSangre(this.cbTipoSangre.getSelectedItem().toString());
               infoGuardar.setTipoSeguro(this.cbSeguroTipo.getSelectedItem().toString());
               if(this.chbDiabetes.isSelected()){
                   infoGuardar.setDiabetes("s");
               }else{
                   infoGuardar.setDiabetes("n");
               }
               if(this.chbHiper.isSelected()){
                   infoGuardar.setHipertención("s");
               }else{
                   infoGuardar.setHipertención("n");
               }
               daoInfo.actualizarInfMedica(infoGuardar, CRUD.estudianteObtenido.getIdEstudiante());
           }else{
               InfoSalud infoGuardar = new InfoSalud();
               infoGuardar.setNumeroSeguro(this.tbNoSeguro.getText());
               infoGuardar.setDiscVisual(this.cbDiscVisual.getSelectedItem().toString());
               infoGuardar.setEstatura(this.cbEstatura.getSelectedItem().toString());
               infoGuardar.setPeso(this.cbPeso.getSelectedItem().toString());
               infoGuardar.setTipoSangre(this.cbTipoSangre.getSelectedItem().toString());
               infoGuardar.setTipoSeguro(this.cbSeguroTipo.getSelectedItem().toString());
               if(this.chbDiabetes.isSelected()){
                   infoGuardar.setDiabetes("s");
               }else{
                   infoGuardar.setDiabetes("n");
               }
               if(this.chbHiper.isSelected()){
                   infoGuardar.setHipertención("s");
               }else{
                   infoGuardar.setHipertención("n");
               }
               daoInfo.actualizarInfMedica(infoGuardar, CRUD.estudianteObtenido.getIdEstudiante());
           }
       }
       JOptionPane.showMessageDialog(null, "Datos guardados correctamente", "Datos guardados",HEIGHT);
       GUIInfoMedica infoMedica = new GUIInfoMedica();
       infoMedica.setVisible(true);
       this.setVisible(false);
       }else{
           JOptionPane.showMessageDialog(null, "Debe de seleccionar todos los campos");
       }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIModificarInfMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIModificarInfMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIModificarInfMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIModificarInfMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIModificarInfMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbDiscVisual;
    private javax.swing.JComboBox<String> cbEstatura;
    private javax.swing.JComboBox<String> cbPeso;
    private javax.swing.JComboBox<String> cbSeguroTipo;
    private javax.swing.JComboBox<String> cbTipoSangre;
    private javax.swing.JCheckBox chbDiabetes;
    private javax.swing.JCheckBox chbHiper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNombreEstudiante;
    private javax.swing.JTextField tbNoSeguro;
    // End of variables declaration//GEN-END:variables
}
