
import DAO.DAOEstudiante;
import DAO.DAOTutor;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pocos.Estudiante;
import pocos.Tutor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eduardo DA
 */
public class RegistrarYModificarTutor extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarYModificarTutor
     */
    ArrayList<Estudiante> estudiantes = new ArrayList<Estudiante>();
    Tutor tutorEditar;
    
    boolean isNuevo;
    
    public RegistrarYModificarTutor() {
        initComponents();
    }
    
    public RegistrarYModificarTutor(boolean isNuevo) {
        initComponents();
        llenarComboBox();
        this.isNuevo = isNuevo;
    }
    public RegistrarYModificarTutor(boolean isNuevo, Tutor tutorEditar) {
        initComponents();
        llenarComboBox();
        this.tutorEditar = tutorEditar;
        this.isNuevo = isNuevo;
        cargarDatosTutor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTitulo = new javax.swing.JLabel();
        BtGuardar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        TfApellidoPaterno = new javax.swing.JTextField();
        TfApellidoMaterno = new javax.swing.JTextField();
        TfDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TfTelefonoFijo = new javax.swing.JTextField();
        TfTelefonoCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CbEstudiante = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LbTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LbTitulo.setText("Registrar Tutor");

        BtGuardar.setText("Guardar");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Apellido Paterno:");

        jLabel4.setText("Apellido Materno:");

        jLabel5.setText("Dirección: ");

        jLabel6.setText("Telefono Fijo: ");

        jLabel7.setText("Telefono Celular: ");

        jLabel8.setText("Estudiante:");

        CbEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(BtCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(63, 63, 63))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfNombre)
                                    .addComponent(TfApellidoPaterno)
                                    .addComponent(TfDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TfApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfTelefonoFijo)
                                    .addComponent(TfTelefonoCelular)
                                    .addComponent(CbEstudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LbTitulo)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TfApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TfTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TfTelefonoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(CbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCancelar)
                    .addComponent(BtGuardar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed

        String nombre = TfNombre.getText();
        String apellidoPaterno = TfApellidoPaterno.getText();
        String apellidoMaterno = TfApellidoMaterno.getText();
        String direccion = TfDireccion.getText();
        String telefonoFijo = TfTelefonoFijo.getText();
        String telefonoCelular = TfTelefonoCelular.getText();
        String idEstudiante = "";
        for(Estudiante estudiante:estudiantes){
            
            if(estudiante.getNombreCompleto().equals(CbEstudiante.getSelectedItem())){
                idEstudiante = estudiante.getIdEstudiante();
            }
        }

        if(nombre.equals("")){
            mensaje("Falta de completar el campo Nombre");
        }else if(apellidoPaterno.equals("") && apellidoMaterno.equals("")){
            mensaje("Debe completar alguno de los campos Apellido Paterno o Apellido Materno");
        }else if(direccion.equals("")){
            mensaje("Falta de completar el campo Direccion");
        } else if(telefonoFijo.equals("") && telefonoCelular.equals("")){
            mensaje("Debe completar alguno de los campos Telefono Fijo o Telefono Celular");
        }else{
            if(isNuevo){
                int resultado;
                resultado = DAOTutor.setTutor(nombre, apellidoMaterno, apellidoPaterno, direccion, telefonoFijo, 
                                          telefonoCelular, idEstudiante);
                if(resultado == 1){
                     mensaje("Se hizo el registro exitosamente");
                }else{
                    mensaje("No se puedo realizar el registro");
                }
                GestionTutor ventanaTutor = new GestionTutor();
                ventanaTutor.setVisible(true);
                this.dispose();
            }else{
                int resultado;
                resultado = DAOTutor.updateTutor(nombre, apellidoMaterno, apellidoPaterno, direccion, 
                                                 telefonoFijo, telefonoCelular, idEstudiante, tutorEditar.getIdTutor());
                
                if(resultado == 1){
                     mensaje("Se hizo la actualización exitosamente");
                }else{
                    mensaje("No se puedo realizar la actualización");
                }
                GestionTutor ventanaTutor = new GestionTutor();
                ventanaTutor.setVisible(true);
                this.dispose();
                
                
            }
        }        
    }//GEN-LAST:event_BtGuardarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        GestionTutor ventanaTutor = new GestionTutor();
        ventanaTutor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtCancelarActionPerformed

    /*
    * Recupera los nombres de los estudiantes
    */
    public void llenarComboBox(){
        estudiantes = DAOEstudiante.ObtenerEstudiantes();
        CbEstudiante.removeAllItems();
        
        for(Estudiante estudiante:estudiantes){
            
            CbEstudiante.addItem(estudiante.getNombreCompleto());
        }   
    }
    
    private void mensaje(String mensaje){
        
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    public void cargarDatosTutor(){
        
        LbTitulo.setText("Editar Tutor" );
        TfNombre.setText(tutorEditar.getNombre());
        TfApellidoPaterno.setText(tutorEditar.getApellidoPaterno());
        TfApellidoMaterno.setText(tutorEditar.getApellidoMaterno());
        TfDireccion.setText(tutorEditar.getDirección());
        TfTelefonoFijo.setText(tutorEditar.getNumeroFijo());
        TfTelefonoCelular.setText(tutorEditar.getNumeroCelular());
        
        for(Estudiante estudiante:estudiantes){
            
            if(estudiante.getIdEstudiante().equals(tutorEditar.getIdEstudiante())){
                CbEstudiante.setSelectedItem(estudiante.getNombreCompleto());
            }
        }
  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarYModificarTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarYModificarTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarYModificarTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarYModificarTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarYModificarTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtGuardar;
    private javax.swing.JComboBox<String> CbEstudiante;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTextField TfApellidoMaterno;
    private javax.swing.JTextField TfApellidoPaterno;
    private javax.swing.JTextField TfDireccion;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JTextField TfTelefonoCelular;
    private javax.swing.JTextField TfTelefonoFijo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
